# Generated by Django 3.0.7 on 2020-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='image/male.png', upload_to='image/')),
                ('bio', models.TextField(blank=True)),
                ('contact_info', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='image/')),
                ('project_title', models.CharField(max_length=60)),
                ('project_description', models.TextField()),
                ('project_link', models.CharField(max_length=150)),
            ],
        ),
    ]
